# Generated by Django 3.1.14 on 2023-02-20 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='redirections_web_qrcodeplugin', serialize=False, to='cms.cmsplugin')),
                ('qr_code', models.ImageField(editable=False, upload_to='qr_code')),
                ('qr_code_link', models.URLField(editable=False, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('external_link', models.URLField(blank=True, choices=[('https://www.shop.lineheart.lu', 'https://www.shop.lineheart.lu'), ('https://lh.lu/s/promo50', 'https://lh.lu/s/promo50')], null=True, verbose_name='External Link')),
                ('name', models.CharField(max_length=60)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('activate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_link', models.ForeignKey(blank=True, help_text='If provided, overrides the external link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page', verbose_name='Internal Link')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
