# Generated by Django 3.1.14 on 2023-02-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirections_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeplugin',
            name='end_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
